// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs-71Kgo-K8aaFvURxjqHPBVtIQPtkMVE',
    appId: '1:690264810434:web:1ef4728ca6b71af9e1ac5b',
    messagingSenderId: '690264810434',
    projectId: 'doantotnghiep-9c859',
    authDomain: 'doantotnghiep-9c859.firebaseapp.com',
    storageBucket: 'doantotnghiep-9c859.firebasestorage.app',
    measurementId: 'G-BSXP310XBE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmeh1rgdEjhxNiL2N_WyrCmjUtWZUaXyA',
    appId: '1:690264810434:android:a80a276d1ea739ece1ac5b',
    messagingSenderId: '690264810434',
    projectId: 'doantotnghiep-9c859',
    storageBucket: 'doantotnghiep-9c859.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF6wZDYkJOUI4NJ_42yzsPFEaO52r5JxI',
    appId: '1:690264810434:ios:1e7e9e805ae47450e1ac5b',
    messagingSenderId: '690264810434',
    projectId: 'doantotnghiep-9c859',
    storageBucket: 'doantotnghiep-9c859.firebasestorage.app',
    iosClientId:
        '690264810434-3ud5gpqca5l2u15sae4dhqr02hlveofc.apps.googleusercontent.com',
    iosBundleId: 'com.legal.consult.client',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCF6wZDYkJOUI4NJ_42yzsPFEaO52r5JxI',
    appId: '1:690264810434:ios:1e7e9e805ae47450e1ac5b',
    messagingSenderId: '690264810434',
    projectId: 'doantotnghiep-9c859',
    storageBucket: 'doantotnghiep-9c859.firebasestorage.app',
    iosClientId:
        '690264810434-3ud5gpqca5l2u15sae4dhqr02hlveofc.apps.googleusercontent.com',
    iosBundleId: 'com.legal.consult.client',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCs-71Kgo-K8aaFvURxjqHPBVtIQPtkMVE',
    appId: '1:690264810434:web:446b88d970ec87b7e1ac5b',
    messagingSenderId: '690264810434',
    projectId: 'doantotnghiep-9c859',
    authDomain: 'doantotnghiep-9c859.firebaseapp.com',
    storageBucket: 'doantotnghiep-9c859.firebasestorage.app',
    measurementId: 'G-385ZL0SCTF',
  );
}
